sudo: required
dist: trusty
language: rust
branches:
  only:
  - master
matrix:
  fast_finish: false
  include:
  - rust: stable
cache:
  apt: true
  directories:
  - "$TRAVIS_BUILD_DIR/target"
  - "$HOME/.cargo"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - gcc-4.8
    - g++-4.8
    - oracle-java8-set-default
script:
- echo 'Running tests' && echo -en 'travis_fold:start:tests'
- cargo test --all
- echo -en 'travis_fold:end:tests'
- echo 'Building in release mode' && echo -en 'travis_fold:start:build.release'
- cargo build --release
- echo -en 'travis_fold:end:build.release'
- echo 'Running bench from ./tools/bench.sh' && echo -en 'travis_fold:start:bench'
- "./tools/bench.sh"
- echo -en 'travis_fold:end:bench'
after_success: |
  [ true ] &&
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  [ $TRAVIS_RUST_VERSION = stable ] &&
  ./tools/doc.sh &&
  echo '<meta http-equiv=refresh content=0;url=pbtc/index.html>' > target/doc/index.html &&
  pip install --user ghp-import &&
  /home/travis/.local/bin/ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
  - CXX="g++-4.8"
  - CC="gcc-4.8"
  - RUST_BACKTRACE=1
  - secure: 3nWI6BU/kmQe154Fq6LYeI4eNsTpu6kRw2lD1fhYgImQDDLKUJ04MHiZqxyUsOBks9m/xNvQqkLLaCmu5/JKy07xnZxc8zkPcVL7dl7fxBvszstsV/nM8fgrSqV6mN3EM83LSttU16y6JfRIlR5E/1s82z7DyCEE9fcpTB8A4Z35eL7g4NHDgG5Fh8HXUft4Yxo6tf1dk6VkiYdFC6n0Hzfm6k+kI29olp+h1aWNoo1bJk+p/t3UwqhaPWNvrl8ijn5AFiA5kE2d7g9WUh65Sp5zJAU5RVdrx1/+pz/rtzWycH3tjTMOsBs82XeRvtBq/PISEgbhK78AAkprvp/l6zes7qM9qZyrtwTnR33WhAVaqkRWE1WCx/KhWBgZErgoVh5EnCc8/8jbo6ghHy9FHOEuO7ikc5use2ODNT2x2RU3KKQaEont8kvvaMIWSxhFErp91Qj8RKx87pS1Ko7Krq6HshJbF1D91PDqdFemTvm8j1iVSX0qx4eON5xkkwy6u+I1D4SAM5C8tggqZHHaOSPIDtIsg949CgbVxTOZjK3RATE/3KmviqekE4xqE0iBo0wJgg7pi1LnKYda4utDr6ljE7kGADZABO0i0tfogV3zQwt5BQDY4EJL9UXU2MsK821T+a8KC2/ig9dSaqNHyHIb1d7FKTySKNzFe+YHMP8=
